_format_version: "3.0"
services:
  - name: user-svc
    url: http://user-svc:3001
    routes:
      - name: user-api
        paths: ["/user"]
  - name: adaptive-svc
    url: http://adaptive-svc:3002
    routes:
      - name: adaptive-api
        paths: ["/adaptive"]
  - name: content-svc
    url: http://content-svc:3003
    routes:
      - name: content-api
        paths: ["/content"]
  - name: analytics-svc
    url: http://analytics-svc:3004
    routes:
      - name: analytics-api
        paths: ["/analytics"]
  - name: engagement-svc
    url: http://engagement-svc:3005
    routes:
      - name: engagement-api
        paths: ["/engagement"]