# Database Performance Optimization Configuration
# This file contains PostgreSQL performance tuning parameters for the adaptive learning platform

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-performance-config
  namespace: adaptive-learning
data:
  postgresql.conf: |
    # Connection Settings
    max_connections = 200
    superuser_reserved_connections = 3
    
    # Memory Settings
    shared_buffers = 256MB                    # 25% of available RAM
    effective_cache_size = 1GB                # 75% of available RAM
    work_mem = 4MB                           # Per-operation memory
    maintenance_work_mem = 64MB              # For maintenance operations
    
    # Checkpoint Settings
    checkpoint_completion_target = 0.9
    checkpoint_timeout = 10min
    max_wal_size = 1GB
    min_wal_size = 80MB
    
    # Query Planner Settings
    random_page_cost = 1.1                   # SSD optimized
    effective_io_concurrency = 200           # SSD optimized
    
    # Logging Settings for Performance Monitoring
    log_min_duration_statement = 1000       # Log queries > 1 second
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    
    # Statistics Settings
    track_activities = on
    track_counts = on
    track_io_timing = on
    track_functions = pl
    
    # Autovacuum Settings
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 20s
    autovacuum_vacuum_threshold = 50
    autovacuum_analyze_threshold = 50
    
    # Connection Pooling Support
    listen_addresses = '*'
    port = 5432
    
    # Performance Extensions
    shared_preload_libraries = 'pg_stat_statements'
    
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             postgres                                peer
    local   all             all                                     md5
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             10.0.0.0/8              md5
    host    replication     all             10.0.0.0/8              md5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: adaptive-learning
data:
  pgbouncer.ini: |
    [databases]
    adaptive_learning = host=postgres-service port=5432 dbname=adaptive_learning
    
    [pgbouncer]
    listen_port = 6432
    listen_addr = *
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    
    # Connection pooling settings
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 50
    min_pool_size = 10
    reserve_pool_size = 10
    reserve_pool_timeout = 5
    
    # Performance settings
    server_reset_query = DISCARD ALL
    server_check_delay = 30
    server_check_query = select 1
    
    # Logging
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    
  userlist.txt: |
    "app_user" "md5d41d8cd98f00b204e9800998ecf8427e"
    "readonly_user" "md5d41d8cd98f00b204e9800998ecf8427e"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: adaptive-learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: pgbouncer/pgbouncer:latest
        ports:
        - containerPort: 6432
        env:
        - name: DATABASES_HOST
          value: "postgres-service"
        - name: DATABASES_PORT
          value: "5432"
        - name: DATABASES_USER
          value: "app_user"
        - name: DATABASES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: app-password
        volumeMounts:
        - name: pgbouncer-config
          mountPath: /etc/pgbouncer
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: pgbouncer-config
        configMap:
          name: pgbouncer-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: adaptive-learning
spec:
  selector:
    app: pgbouncer
  ports:
  - port: 6432
    targetPort: 6432
  type: ClusterIP