apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: adaptive-learning-prod
  labels:
    app: event-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-service
      version: v1
  template:
    metadata:
      labels:
        app: event-service
        version: v1
    spec:
      containers:
      - name: event-service
        image: adaptive-learning/event-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: event-service-config
              key: PORT
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: kafka-credentials
              key: KAFKA_BROKERS
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: event-service-config
              key: BATCH_SIZE
        - name: FLUSH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: event-service-config
              key: FLUSH_INTERVAL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: adaptive-learning-prod
  labels:
    app: event-service
spec:
  selector:
    app: event-service
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event-service-hpa
  namespace: adaptive-learning-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80