apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: adaptive-learning-prod
  labels:
    app: fraud-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-service
      version: v1
  template:
    metadata:
      labels:
        app: fraud-service
        version: v1
    spec:
      containers:
      - name: fraud-service
        image: adaptive-learning/fraud-service:latest
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: fraud-service-config
              key: PORT
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: kafka-credentials
              key: KAFKA_BROKERS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        - name: ANOMALY_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: fraud-service-config
              key: ANOMALY_THRESHOLD
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: adaptive-learning-prod
  labels:
    app: fraud-service
spec:
  selector:
    app: fraud-service
  ports:
  - port: 8003
    targetPort: 8003
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraud-service-hpa
  namespace: adaptive-learning-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraud-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80