apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: adaptive-learning-prod
  labels:
    app: ml-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-service
      version: v1
  template:
    metadata:
      labels:
        app: ml-service
        version: v1
    spec:
      containers:
      - name: ml-service
        image: adaptive-learning/ml-service:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ml-service-config
              key: PORT
        - name: MODEL_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: ml-service-config
              key: MODEL_REGISTRY_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_URL
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: ml-service-config
              key: BATCH_SIZE
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
            nvidia.com/gpu: 0
          limits:
            memory: "2Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: adaptive-learning-prod
  labels:
    app: ml-service
spec:
  selector:
    app: ml-service
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-service-hpa
  namespace: adaptive-learning-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80