apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  namespace: adaptive-learning-prod
  labels:
    app: scheduler-service
    version: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scheduler-service
      version: v1
  template:
    metadata:
      labels:
        app: scheduler-service
        version: v1
    spec:
      containers:
      - name: scheduler-service
        image: adaptive-learning/scheduler-service:latest
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9091
          name: grpc
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: scheduler-service-config
              key: PORT
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: scheduler-service-config
              key: GRPC_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: REDIS_URL
        - name: ALGORITHM_WEIGHTS
          valueFrom:
            configMapKeyRef:
              name: scheduler-service-config
              key: ALGORITHM_WEIGHTS
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: adaptive-learning-prod
  labels:
    app: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 9091
    targetPort: 9091
    name: grpc
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scheduler-service-hpa
  namespace: adaptive-learning-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scheduler-service
  minReplicas: 4
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80