version: "3.8"

services:
  # Redis Cluster Nodes
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    ports:
      - "7001:7000"
      - "17001:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_1_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-1
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.11
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    ports:
      - "7002:7000"
      - "17002:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_2_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-2
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.12
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    ports:
      - "7003:7000"
      - "17003:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_3_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-3
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.13
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node-4:
    image: redis:7-alpine
    container_name: redis-node-4
    ports:
      - "7004:7000"
      - "17004:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_4_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-4
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.14
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node-5:
    image: redis:7-alpine
    container_name: redis-node-5
    ports:
      - "7005:7000"
      - "17005:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_5_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-5
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.15
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node-6:
    image: redis:7-alpine
    container_name: redis-node-6
    ports:
      - "7006:7000"
      - "17006:17000"
    volumes:
      - ./redis-cluster.conf:/usr/local/etc/redis/redis.conf
      - redis_node_6_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000 --cluster-announce-ip redis-node-6
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.16
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-p",
          "7000",
          "-a",
          "redis_cluster_password_2024!",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cluster Initialization
  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      redis-node-1:
        condition: service_healthy
      redis-node-2:
        condition: service_healthy
      redis-node-3:
        condition: service_healthy
      redis-node-4:
        condition: service_healthy
      redis-node-5:
        condition: service_healthy
      redis-node-6:
        condition: service_healthy
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.10
    command: >
      sh -c "
        echo 'Waiting for Redis nodes to be ready...' &&
        sleep 10 &&
        echo 'Creating Redis cluster...' &&
        redis-cli -a redis_cluster_password_2024! --cluster create 
        redis-node-1:7000 
        redis-node-2:7000 
        redis-node-3:7000 
        redis-node-4:7000 
        redis-node-5:7000 
        redis-node-6:7000 
        --cluster-replicas 1 --cluster-yes &&
        echo 'Redis cluster created successfully!' &&
        echo 'Cluster info:' &&
        redis-cli -c -h redis-node-1 -p 7000 -a redis_cluster_password_2024! cluster info &&
        echo 'Cluster nodes:' &&
        redis-cli -c -h redis-node-1 -p 7000 -a redis_cluster_password_2024! cluster nodes
      "

  # Redis Sentinel for monitoring (optional but recommended)
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.21
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.22
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.23
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  # Redis Exporter for Prometheus monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis-node-1:7000,redis://redis-node-2:7000,redis://redis-node-3:7000"
      REDIS_PASSWORD: "redis_cluster_password_2024!"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.30
    depends_on:
      - redis-cluster-init

volumes:
  redis_node_1_data:
  redis_node_2_data:
  redis_node_3_data:
  redis_node_4_data:
  redis_node_5_data:
  redis_node_6_data:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
