# Service Level Objectives (SLO) Configuration for DriveMaster Platform
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-config
  namespace: drivemaster
data:
  slo-rules.yaml: |
    groups:
      - name: drivemaster.slo
        interval: 30s
        rules:
          # Availability SLI - 99.9% uptime target
          - record: sli:availability:rate5m
            expr: |
              (
                sum(rate(http_requests_total{job=~".*-service"}[5m])) -
                sum(rate(http_requests_total{job=~".*-service", status=~"5.."}[5m]))
              ) / sum(rate(http_requests_total{job=~".*-service"}[5m]))

          - alert: SLOAvailabilityBreach
            expr: sli:availability:rate5m < 0.999
            for: 2m
            labels:
              severity: critical
              slo: availability
            annotations:
              summary: "Availability SLO breach detected"
              description: "Service availability is {{ $value | humanizePercentage }}, below 99.9% target"

          # Latency SLI - 95% of requests under 100ms
          - record: sli:latency:p95:rate5m
            expr: |
              histogram_quantile(0.95,
                sum(rate(http_request_duration_seconds_bucket{job=~".*-service"}[5m])) by (le)
              )

          - alert: SLOLatencyBreach
            expr: sli:latency:p95:rate5m > 0.1
            for: 5m
            labels:
              severity: warning
              slo: latency
            annotations:
              summary: "Latency SLO breach detected"
              description: "95th percentile latency is {{ $value }}s, above 100ms target"

          # Error Rate SLI - Less than 0.1% error rate
          - record: sli:error_rate:rate5m
            expr: |
              sum(rate(http_requests_total{job=~".*-service", status=~"5.."}[5m])) /
              sum(rate(http_requests_total{job=~".*-service"}[5m]))

          - alert: SLOErrorRateBreach
            expr: sli:error_rate:rate5m > 0.001
            for: 1m
            labels:
              severity: critical
              slo: error_rate
            annotations:
              summary: "Error rate SLO breach detected"
              description: "Error rate is {{ $value | humanizePercentage }}, above 0.1% target"

          # Learning Effectiveness SLI - Maintain above 75% effectiveness
          - record: sli:learning_effectiveness:avg1h
            expr: |
              avg_over_time(learning_effectiveness_score[1h])

          - alert: SLOLearningEffectivenessBreach
            expr: sli:learning_effectiveness:avg1h < 0.75
            for: 10m
            labels:
              severity: warning
              slo: learning_effectiveness
            annotations:
              summary: "Learning effectiveness SLO breach detected"
              description: "Learning effectiveness is {{ $value | humanizePercentage }}, below 75% target"

          # User Engagement SLI - Average session duration above 5 minutes
          - record: sli:user_engagement:avg1h
            expr: |
              avg_over_time(user_session_duration_seconds[1h])

          - alert: SLOUserEngagementBreach
            expr: sli:user_engagement:avg1h < 300
            for: 15m
            labels:
              severity: warning
              slo: user_engagement
            annotations:
              summary: "User engagement SLO breach detected"
              description: "Average session duration is {{ $value }}s, below 5 minute target"

          # Data Freshness SLI - Analytics data processed within 1 minute
          - record: sli:data_freshness:max5m
            expr: |
              max_over_time(analytics_processing_delay_seconds[5m])

          - alert: SLODataFreshnessBreach
            expr: sli:data_freshness:max5m > 60
            for: 2m
            labels:
              severity: warning
              slo: data_freshness
            annotations:
              summary: "Data freshness SLO breach detected"
              description: "Analytics processing delay is {{ $value }}s, above 60s target"

          # Infrastructure SLIs
          - record: sli:database_availability:rate5m
            expr: |
              avg_over_time(pg_up[5m])

          - alert: SLODatabaseAvailabilityBreach
            expr: sli:database_availability:rate5m < 1
            for: 30s
            labels:
              severity: critical
              slo: database_availability
            annotations:
              summary: "Database availability SLO breach detected"
              description: "Database availability is {{ $value | humanizePercentage }}"

          - record: sli:cache_hit_ratio:avg5m
            expr: |
              avg_over_time(redis_keyspace_hits_total[5m]) /
              (avg_over_time(redis_keyspace_hits_total[5m]) + avg_over_time(redis_keyspace_misses_total[5m]))

          - alert: SLOCacheHitRatioBreach
            expr: sli:cache_hit_ratio:avg5m < 0.95
            for: 5m
            labels:
              severity: warning
              slo: cache_performance
            annotations:
              summary: "Cache hit ratio SLO breach detected"
              description: "Cache hit ratio is {{ $value | humanizePercentage }}, below 95% target"

      # Error Budget Tracking
      - name: drivemaster.error_budget
        interval: 1m
        rules:
          # Monthly error budget (99.9% availability = 43.2 minutes downtime per month)
          - record: error_budget:availability:monthly
            expr: |
              1 - (
                (1 - sli:availability:rate5m) * 
                (30 * 24 * 60) / 43.2
              )

          - record: error_budget:latency:monthly
            expr: |
              1 - (
                (sli:latency:p95:rate5m > 0.1) * 
                (30 * 24 * 60) / (30 * 24 * 60 * 0.05)
              )

          - record: error_budget:error_rate:monthly
            expr: |
              1 - (
                sli:error_rate:rate5m * 
                (30 * 24 * 60) / (30 * 24 * 60 * 0.001)
              )

          # Error budget burn rate alerts
          - alert: ErrorBudgetBurnRateHigh
            expr: |
              (
                error_budget:availability:monthly < 0.9 or
                error_budget:latency:monthly < 0.9 or
                error_budget:error_rate:monthly < 0.9
              )
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High error budget burn rate detected"
              description: "Error budget is being consumed rapidly"

          - alert: ErrorBudgetExhausted
            expr: |
              (
                error_budget:availability:monthly < 0.1 or
                error_budget:latency:monthly < 0.1 or
                error_budget:error_rate:monthly < 0.1
              )
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Error budget nearly exhausted"
              description: "Less than 10% of monthly error budget remaining"

  slo-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "DriveMaster SLO Dashboard",
        "tags": ["slo", "sli", "reliability"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Availability SLI",
            "type": "stat",
            "targets": [
              {
                "expr": "sli:availability:rate5m"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "min": 0.99,
                "max": 1,
                "thresholds": {
                  "steps": [
                    {
                      "color": "red",
                      "value": 0
                    },
                    {
                      "color": "yellow",
                      "value": 0.999
                    },
                    {
                      "color": "green",
                      "value": 0.9995
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Latency SLI (95th percentile)",
            "type": "stat",
            "targets": [
              {
                "expr": "sli:latency:p95:rate5m"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "s",
                "max": 0.2,
                "thresholds": {
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    },
                    {
                      "color": "yellow",
                      "value": 0.1
                    },
                    {
                      "color": "red",
                      "value": 0.15
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 6,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "Error Rate SLI",
            "type": "stat",
            "targets": [
              {
                "expr": "sli:error_rate:rate5m"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "max": 0.01,
                "thresholds": {
                  "steps": [
                    {
                      "color": "green",
                      "value": 0
                    },
                    {
                      "color": "yellow",
                      "value": 0.001
                    },
                    {
                      "color": "red",
                      "value": 0.005
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 4,
            "title": "Learning Effectiveness SLI",
            "type": "stat",
            "targets": [
              {
                "expr": "sli:learning_effectiveness:avg1h"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "min": 0.5,
                "max": 1,
                "thresholds": {
                  "steps": [
                    {
                      "color": "red",
                      "value": 0
                    },
                    {
                      "color": "yellow",
                      "value": 0.75
                    },
                    {
                      "color": "green",
                      "value": 0.85
                    }
                  ]
                }
              }
            },
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 18,
              "y": 0
            }
          },
          {
            "id": 5,
            "title": "Error Budget Consumption",
            "type": "graph",
            "targets": [
              {
                "expr": "error_budget:availability:monthly",
                "legendFormat": "Availability"
              },
              {
                "expr": "error_budget:latency:monthly",
                "legendFormat": "Latency"
              },
              {
                "expr": "error_budget:error_rate:monthly",
                "legendFormat": "Error Rate"
              }
            ],
            "yAxes": [
              {
                "min": 0,
                "max": 1,
                "unit": "percentunit"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 24,
              "x": 0,
              "y": 4
            }
          }
        ],
        "time": {
          "from": "now-24h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }