apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-database
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  DATABASE_URL: {{ include "adaptive-learning.databaseUrl" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_HOST: {{ .Release.Name }}-redis-master
  REDIS_PORT: "6379"
  REDIS_PASSWORD: {{ .Values.redis.auth.password }}
  REDIS_URL: {{ include "adaptive-learning.redisUrl" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_BROKERS: {{ include "adaptive-learning.kafkaBrokers" . }}
  KAFKA_SCHEMA_REGISTRY_URL: http://{{ .Release.Name }}-kafka-schema-registry:8081
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-jwt
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwt.secret }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwt.refreshSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-oauth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: {{ .Values.secrets.oauth.googleClientId }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.oauth.googleClientSecret }}
  APPLE_CLIENT_ID: {{ .Values.secrets.oauth.appleClientId }}
  APPLE_CLIENT_SECRET: {{ .Values.secrets.oauth.appleClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-s3
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.s3.secretAccessKey }}
  AWS_REGION: {{ .Values.secrets.s3.region }}
  S3_BUCKET: {{ .Values.secrets.s3.bucket }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptive-learning.fullname" . }}-notifications
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adaptive-learning.labels" . | nindent 4 }}
type: Opaque
stringData:
  FCM_SERVER_KEY: {{ .Values.secrets.notifications.fcmServerKey }}
  APNS_KEY_ID: {{ .Values.secrets.notifications.apnsKeyId }}
  APNS_TEAM_ID: {{ .Values.secrets.notifications.apnsTeamId }}
  APNS_PRIVATE_KEY: {{ .Values.secrets.notifications.apnsPrivateKey }}