global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "kafka_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Kafka JMX metrics
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka-1:19092', 'kafka-2:19093', 'kafka-3:19094']
    scrape_interval: 10s
    metrics_path: /metrics

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s

  # Zookeeper Exporter
  - job_name: 'zookeeper-exporter'
    static_configs:
      - targets: ['zookeeper-exporter:9141']
    scrape_interval: 10s

  # Schema Registry metrics
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  # Kafka Connect metrics
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083']
    metrics_path: /metrics
    scrape_interval: 10s

  # Application services metrics
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8082']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8083']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'fraud-service'
    static_configs:
      - targets: ['fraud-service:8004']
    metrics_path: /metrics
    scrape_interval: 10s