apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: adaptive-learning-monitoring
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alerts@adaptivelearning.com'
      smtp_auth_username: 'alerts@adaptivelearning.com'
      smtp_auth_password: 'your-app-password'  # Use app password for Gmail
      slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default-receiver'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        repeat_interval: 30m
      - match:
          severity: warning
        receiver: 'warning-alerts'
        group_wait: 30s
        repeat_interval: 2h
      - match:
          alertname: ServiceDown
        receiver: 'service-down-alerts'
        group_wait: 0s
        repeat_interval: 15m
      - match:
          alertname: HighErrorRate
        receiver: 'error-rate-alerts'
        group_wait: 10s
        repeat_interval: 1h
      - match_re:
          alertname: ^(MLModel|Scheduler).*
        receiver: 'ml-scheduler-alerts'
        group_wait: 15s
        repeat_interval: 1h

    receivers:
    - name: 'default-receiver'
      slack_configs:
      - channel: '#alerts'
        title: 'Adaptive Learning Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.job }}
          {{ end }}
        send_resolved: true

    - name: 'critical-alerts'
      slack_configs:
      - channel: '#critical-alerts'
        title: '🚨 CRITICAL: Adaptive Learning Alert'
        text: |
          {{ range .Alerts }}
          *CRITICAL ALERT:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.job }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true
      email_configs:
      - to: 'oncall@adaptivelearning.com'
        subject: 'CRITICAL: {{ .GroupLabels.alertname }} - Adaptive Learning Platform'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.job }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

    - name: 'warning-alerts'
      slack_configs:
      - channel: '#warnings'
        title: '⚠️ WARNING: Adaptive Learning Alert'
        text: |
          {{ range .Alerts }}
          *Warning:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.job }}
          {{ end }}
        send_resolved: true

    - name: 'service-down-alerts'
      slack_configs:
      - channel: '#critical-alerts'
        title: '🔴 SERVICE DOWN: {{ .GroupLabels.job }}'
        text: |
          {{ range .Alerts }}
          *SERVICE DOWN:* {{ .Labels.job }}
          *Description:* {{ .Annotations.description }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true
      email_configs:
      - to: 'oncall@adaptivelearning.com'
        subject: 'SERVICE DOWN: {{ .GroupLabels.job }} - Immediate Action Required'
        body: |
          {{ range .Alerts }}
          SERVICE DOWN: {{ .Labels.job }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Please investigate immediately.
          {{ end }}

    - name: 'error-rate-alerts'
      slack_configs:
      - channel: '#alerts'
        title: '📈 HIGH ERROR RATE: {{ .GroupLabels.job }}'
        text: |
          {{ range .Alerts }}
          *High Error Rate:* {{ .Labels.job }}
          *Description:* {{ .Annotations.description }}
          *Current Rate:* {{ .Annotations.value }}
          {{ end }}
        send_resolved: true

    - name: 'ml-scheduler-alerts'
      slack_configs:
      - channel: '#ml-alerts'
        title: '🤖 ML/Scheduler Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *ML/Scheduler Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.job }}
          *Value:* {{ .Annotations.value }}
          {{ end }}
        send_resolved: true
      email_configs:
      - to: 'ml-team@adaptivelearning.com'
        subject: 'ML/Scheduler Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.job }}
          Value: {{ .Annotations.value }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
    - source_match:
        alertname: 'ServiceDown'
      target_match_re:
        alertname: '^(HighErrorRate|HighResponseTime|HighMemoryUsage|HighCPUUsage)$'
      equal: ['job']