global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'drivemaster-dev'
    environment: 'development'

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application Services
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-svc:3001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'adaptive-service'
    static_configs:
      - targets: ['adaptive-svc:3002']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-svc:3003']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-svc:3004']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'engagement-service'
    static_configs:
      - targets: ['engagement-svc:3005']
    metrics_path: /metrics
    scrape_interval: 15s

  # Infrastructure Components
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s