apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: adaptive-learning-monitoring
  labels:
    app: grafana
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "15s"
        queryTimeout: "60s"
        httpMethod: "POST"
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      editable: true
      jsonData:
        maxLines: 1000
        timeout: 60
        
  dashboards.yml: |
    apiVersion: 1
    providers:
    - name: 'adaptive-learning-dashboards'
      orgId: 1
      folder: 'Adaptive Learning'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
        
  notifiers.yml: |
    notifiers:
    - name: slack-alerts
      type: slack
      uid: slack-alerts
      org_id: 1
      is_default: true
      send_reminder: true
      disable_resolve_message: false
      frequency: "10s"
      settings:
        url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#alerts"
        username: "Grafana"
        title: "Adaptive Learning Alert"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}"