groups:
  - name: drivemaster.infrastructure
    rules:
      # PostgreSQL Alerts
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 30s
        labels:
          severity: critical
          component: "postgresql"
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 30 seconds"

      - alert: PostgreSQLHighConnections
        expr: (pg_stat_activity_count / pg_settings_max_connections) * 100 > 80
        for: 2m
        labels:
          severity: warning
          component: "postgresql"
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "Connection usage is {{ $value }}%"

      - alert: PostgreSQLLowCacheHitRatio
        expr: pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read) * 100 < 95
        for: 5m
        labels:
          severity: warning
          component: "postgresql"
        annotations:
          summary: "PostgreSQL low cache hit ratio"
          description: "Cache hit ratio is {{ $value }}%"

      - alert: PostgreSQLReplicationLag
        expr: pg_replication_lag_seconds > 30
        for: 1m
        labels:
          severity: critical
          component: "postgresql"
        annotations:
          summary: "PostgreSQL replication lag"
          description: "Replication lag is {{ $value }}s"

      # Redis Alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 30s
        labels:
          severity: critical
          component: "redis"
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 30 seconds"

      - alert: RedisHighMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 2m
        labels:
          severity: warning
          component: "redis"
        annotations:
          summary: "Redis high memory usage"
          description: "Memory usage is {{ $value }}%"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 1000
        for: 2m
        labels:
          severity: warning
          component: "redis"
        annotations:
          summary: "Redis high connection count"
          description: "Connected clients: {{ $value }}"

      # Kafka Alerts
      - alert: KafkaDown
        expr: kafka_server_brokertopicmetrics_messagesin_total == 0
        for: 1m
        labels:
          severity: critical
          component: "kafka"
        annotations:
          summary: "Kafka broker appears down"
          description: "No messages received in the last minute"

      - alert: KafkaHighLag
        expr: kafka_consumer_lag_sum > 1000
        for: 2m
        labels:
          severity: warning
          component: "kafka"
        annotations:
          summary: "Kafka consumer lag is high"
          description: "Consumer lag is {{ $value }} messages"

      # Elasticsearch Alerts
      - alert: ElasticsearchDown
        expr: elasticsearch_cluster_health_up == 0
        for: 30s
        labels:
          severity: critical
          component: "elasticsearch"
        annotations:
          summary: "Elasticsearch is down"
          description: "Elasticsearch cluster has been down for more than 30 seconds"

      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 1m
        labels:
          severity: critical
          component: "elasticsearch"
        annotations:
          summary: "Elasticsearch cluster status is red"
          description: "Elasticsearch cluster health is red"

      - alert: ElasticsearchHighDiskUsage
        expr: (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes) / elasticsearch_filesystem_data_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: "elasticsearch"
        annotations:
          summary: "Elasticsearch high disk usage"
          description: "Disk usage is {{ $value }}%"

      # System Alerts
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: "system"
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value }}% on {{ $labels.device }}"

      - alert: HighSystemLoad
        expr: node_load1 > 4
        for: 2m
        labels:
          severity: warning
          component: "system"
        annotations:
          summary: "High system load"
          description: "System load is {{ $value }}"